### PR TITLE
[Batch 1] Port Notebook PRs

### PR DESCRIPTION
**Pull request by Zsailer**
For more details about these PRs, see 

- [x] jupyter/notebook#3664
- [x] jupyter/notebook#3759
- [x] jupyter/notebook#3778
- [x] jupyter/notebook#3809
- [x] jupyter/notebook#3829

### CODE REVIEW

**Comment by vidartf** [comment]
Some of these seem to undo some things from https://github.com/jupyter/jupyter_server/pull/94 ?

**Comment by vidartf** [comment]
Or rather, contrary to that PR.

**Comment by Zsailer** [comment]
You're right. This is the challenge of cherry-picking PRs. I'll remove the Python2/3 patches in a new commit (rather than removing specific commits). Does that seem reasonable?

**Comment by kevin-bates** [comment]
Shoot.  We should probably complete the initial migration from Notebook before doing "new" things.  Sorry about that.  Nice catch @vidartf.

**Comment by kevin-bates** [comment]
#96: Remove commit 349045e - ip_address only accepts unicode on Python 2

**Pull request merged**
