### PR TITLE
Add .vscode to gitignore

### PR DESCRIPTION
**Pull request by jtpio**

### CODE REVIEW

**Comment by jtpio** [comment]
All GitHub Actions tests seem to be failing (same as in https://github.com/jupyter/jupyter_server/pull/175).

**Comment by Zsailer** [comment]
Thanks @jtpio!

We're failing tests are due to an issue in pytest. #177 includes a commit that pins pytest to a working version.

**Comment by jtpio** [comment]
Let me rebase that quickly then!

**Comment by jtpio** [comment]
All green now.

**Pull request merged**
