### PR TITLE
Scan with CodeQL

### PR DESCRIPTION
**Pull request by jasongrout**
This will help track down issues like unused imports, etc. See https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository

Results at https://github.com/jupyter/jupyter_server/security/code-scanning?query=tool%3ACodeQL+is%3Aopen+ref%3Arefs%2Fpull%2F332%2Fmerge

### CODE REVIEW

**Comment by jasongrout** [comment]
Codeql reports 147 issues. Lots of low-hanging fruit there to tackle.

**Comment by jasongrout** [comment]
(I think we could merge this to expose the report, then resolving the reported issues can be low-hanging maintenance tasks)

**Review by echarles — APPROVED** [review]

**Comment by echarles** [comment]
Thx @jasongrout I guess a next step will be to open an issue with the report.

**Comment by jasongrout** [comment]
> Thx @jasongrout I guess a next step will be to open an issue with the report.

The alerts are now available from the Security tab: https://github.com/jupyter/jupyter_server/security/code-scanning

I think from here it is just opening PRs fixing them.

**Comment by kevin-bates** [comment]
I would like that all pushed branches trigger this report so that would-be pull requests could first have a chance to address any flagged issues.  I'll provide a PR to make that change.

Overall, this seems a little invasive in my opinion.  For example, the [tests re-use `r` to hold responses](https://github.com/jupyter/jupyter_server/security/code-scanning/139?query=ref%3Arefs%2Fheads%2Fmaster) all over the place.  

If a given flagged issue is dismissed, do you know if it records that dismissal so as to not raise it again?   [I guess I need to go look at CodeQL.](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/triaging-code-scanning-alerts-in-pull-requests#dismissing-an-alert-on-your-pull-request)

**Comment by jasongrout** [comment]
> If a given flagged issue is dismissed, do you know if it records that dismissal so as to not raise it again? [I guess I need to go look at CodeQL.](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/triaging-code-scanning-alerts-in-pull-requests#dismissing-an-alert-on-your-pull-request)

I think so? At least, that would make sense to me.

**Comment by kevin-bates** [comment]
Yeah, after looking at the results on my pushed branch (for #333), no new alerts were found so the security tab represents an accumulation of whatever has been encountered, which, I agree, must consist of some persisted state.

Once we get the flagged issues addressed, things will settle down (in my head :smile: ).

**Comment by farisachugthai** [comment]
Hey I'm sorry @jasongrout but I might be missing something here. The results link provided doesn't seem to be working and the security/code-scanning isn't working either.

I tried looking under actions to see the code scan being run in this repos workflow but couldn't locate that either.

Id definitely be interested in helping to fix these issues but unless I'm missing something I can't see the results 😞

**Pull request merged**
