### PR TITLE
Remove travis and appveyor build

### PR DESCRIPTION
**Pull request by echarles**
Let's wait a bit to have full confidence in github actions, then let's remove travis build.

### CODE REVIEW

**Comment by kevin-bates** [comment]
This looks good. 

Should the same fate come of appveyor as well since GH actions run Windows servers?
I would recommend an indicator in the title that indicates not to merge, perhaps either [WIP] or [DO NOT MERGE].

**Comment by echarles** [comment]
I/we have less access to windows (which is server 2019 for github actions) and prefer having a fallback in case of failure to see how it behaves on other windows flavors.

**Comment by echarles** [comment]
@kevin-bates @Zsailer any objection to process with this to remove travis and appveyor, see https://github.com/kevin-bates/jupyter_server/pull/1 ?

**Comment by echarles** [comment]
As discussed during the server meeting, this PR remove now travis and appveyor CI build.

**Comment by Zsailer** [comment]
Let's wait until Thursday's meeting to merge. I'm stoked about this! 😎

**Pull request merged**
