### PR TITLE
cleaning up PR#113

### PR DESCRIPTION
**Pull request by Zsailer**
Fixing comments from #113. 

@vidartf

### CODE REVIEW

**Comment by vidartf** [comment]
Thanks! I'm happy to merge this as is. I'll do another pass on the full changes after, especially w.r.t. writing some more tests (the issues I pointed out should ideally have been picked up by some tests).

**Comment by Zsailer** [comment]
@vidartf :+1:

Sounds good. Merge away. Thanks for your help reviewing!

**Comment by echarles** [comment]
Have not tested this PR but from the diff, it sounds like a needed change that will fix the absence of token when the browser is launched. LGTM.

**Comment by vidartf** [comment]
> Sounds good. Merge away. Thanks for your help reviewing!

I don't have merge rights though, so someone else would have to push the button. 😉

**Comment by vidartf** [comment]
I.e. ~I'm happy to merge this as is.~ -> I'm happy for this to be merged as-is

**Pull request merged**
