### PR TITLE
Fix the non-writable path deletion error

### PR DESCRIPTION
**Pull request by vkaidalov**
Hi everyone!

I noticed that I got the "Delete Failed: Unhandled error" message in the error dialog when I tried to delete either a read-only file or a read-only directory. In contrast, the message was "Permission denied" in JupyterLab 1.x, so I decided to take a look at the code.

As the result, I found out that this issue had already been identified in the comments. Given that the "easier to ask for forgiveness than permission" approach cannot be used there because of send2trash's errors ambiguity, I propose to "look before you leap" to fix this issue.

Could you please review the PR? It should make the server return 403 instead of 500 and also make JupyterLab show the "Permission denied" message instead of the "Unhandled error" text. I've also moved the permissions check code to a separate new method.

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
LGTM, thank you!

**Comment by blink1073** [comment]
Kicking CI

**Comment by Zsailer** [comment]
Kicking CI one more time after #669

**Comment by blink1073** [comment]
Kicking to pick up windows skips

**Comment by blink1073** [comment]
CI failures are unrelated and captured in #677.  Thanks again @vkaidalov!

**Pull request merged**
