### PR TITLE
Applied fix for secure writes in non-enlgish windows that was added to jupyer_client

### PR DESCRIPTION
**Pull request by MSeal**
See https://github.com/jupyter/jupyter_client/pull/478 for details, but this should be included in the next release.

### CODE REVIEW

**Comment by MSeal** [comment]
@rgbkrk @rolweber FYI

**Comment by kevin-bates** [comment]
Thanks for dealing with this @MSeal!

Is there any reason we can't switch to using the functions from jupyter_client (5.3.3)?  Ideally, as the `#TODO` points out, we want these in `jupyter_core` but that's probably a different move. 

((Note: If/when we switch to using the [jupyter_kernel_mgmt](https://github.com/takluyver/jupyter_kernel_mgmt) stuff `jupyter_client` goes away but we'll need to update the spec kernel provider [here](https://github.com/takluyver/jupyter_kernel_mgmt/blob/master/jupyter_kernel_mgmt/subproc/launcher.py#L122-L123).))

**Comment by MSeal** [comment]
@kevin-bates You likely want to either copy the functions -- or help get someone to merge https://github.com/jupyter/jupyter_core/pull/163 so it's available from core :)

There was a security advisory that some internal secret files weren't guaranteed to be saved to permission secured files. In most cases the default behavior is fine but in some setups it exposes files to be read / written by adjacent (or anonymous) users.

**Comment by MSeal** [comment]
In the meanwhile loading it from jupyter_client is probably fine if you already have the dependency added anyway.

**Comment by kevin-bates** [comment]
@MSeal - dang, I didn't realize I hadn't been watching core - thank you!

**Comment by Zsailer** [comment]
Thanks, @MSeal! LGTM.

**Comment by rolweber** [comment]
I'll merge this as-is. If we switch to using the function from jupyter_client, that should be done with a separate PR.

**Comment by rgbkrk** [comment]
Thank you all!

**Pull request merged**
