### PR TITLE
Ensure nested static content is published to pypi

### PR DESCRIPTION
**Pull request by echarles**
Ensure nested static content is published to pypi so the favicons are availble on install

cc/ @blink1073

### CODE REVIEW

**Comment by blink1073** [comment]
Published `jupyter_server-1.0.0rc9`

**Comment by blink1073** [comment]
Static assets are still not published:

```
(jlab-master) stslve: ~/miniconda/envs/jlab-master/lib/python3.7/site-packages/jupyter_server
$ ls
.                 __pycache__       auth              extension         kernelspecs       pytest_plugin.py  terminal
..                _sysinfo.py       base              files             log.py            serverapp.py      transutils.py
__init__.py       _tz.py            config_manager.py gateway           nbconvert         services          utils.py
__main__.py       _version.py       edit              i18n              prometheus        templates         view
```

**Comment by echarles** [comment]
@blink1073 they are under jupyter_server/static

```
 datalayer  ~  Downloads  jupyter_server-1.0.0rc9  jupyter_server  static  $  tree
bash: tree: command not found
 datalayer  ~  Downloads  jupyter_server-1.0.0rc9  jupyter_server  static  $  ll
total 64
drwxr-xr-x@  5 echar4  staff    160 27 Aug 17:57 ./
drwxr-xr-x@ 28 echar4  staff    896 27 Aug 17:57 ../
-rw-r--r--@  1 echar4  staff  32038  4 Aug 18:37 favicon.ico
drwxr-xr-x@  9 echar4  staff    288 27 Aug 17:57 favicons/
drwxr-xr-x@  3 echar4  staff     96 27 Aug 17:57 logo/
 datalayer  ~  Downloads  jupyter_server-1.0.0rc9  jupyter_server  static  $  ls favicons/
favicon-busy-1.ico      favicon-busy-2.ico      favicon-busy-3.ico      favicon-file.ico        favicon-notebook.ico    favicon-terminal.ico    favicon.ico
```

**Comment by blink1073** [comment]
Hmm, the static dir is in the tarball but not in the published wheel.

**Pull request merged**
