### PR TITLE
Drop support for python 3.5

### PR DESCRIPTION
**Pull request by blink1073**
JupyterLab is dropping support for Python 3.5 in 3.0, see also https://numpy.org/neps/nep-0029-deprecation_policy.html

### CODE REVIEW

**Comment by jasongrout** [comment]
> JupyterLab is dropping support for Python 3.5 in 3.0

When was this decided?

**Comment by jasongrout** [comment]
Duh: https://github.com/jupyterlab/jupyterlab/pull/8903

Sometimes I don't know where my head is :)

**Comment by blink1073** [comment]
:smile:

**Comment by jasongrout** [comment]
Oh, I think the reason I didn't push that change down to this level is that Notebook 6 supports python 3.5, and I thought we wanted nbclassic to be a drop-in replacement. So I thought that supporting python 3.5 was deliberate for jupyter_server to make *sure* people could migrate off notebook.

**Comment by Zsailer** [comment]
I think since Python 3.5 reaches end-of-life on 9/13, we can ask that people move off in jupyter_server **and** Notebook at this point. I'm planning to submit a PR to remove Python 3.5 from Notebook too.

**Pull request merged**
